[test.validator]
url = "devnet"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"


[features]
seeds = false
[programs.localnet]
jmint = "8GoXp1CfyXrCt9H7jynCzxMyw65XGECHGQM5MDE7qrxC"

[programs.devnet]
jmint = "8GoXp1CfyXrCt9H7jynCzxMyw65XGECHGQM5MDE7qrxC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
